# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True
val_interval: 1

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
batch_size: 512

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
vflip: 0.0
interpolation: "bicubic"
auto_augment: "randaug-m9-mstd0.5"
re_prob: 0.0
cutmix: 1.0
cutmix_prob: 1.0
mixup: 0.8

# model
model: "vit_l_16_224"
num_classes: 1000
drop_rate: 0.15
drop_path_rate: 0.2
keep_checkpoint_max: 10
ckpt_save_dir: "./ckpt"
ckpt_save_interval: 1
ckpt_save_policy: "top_k"
epoch_size: 300
dataset_sink_mode: True

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
lr: 1.6e-3
min_lr: 0.0
warmup_epochs: 30
decay_epochs: 270
warmup_factor: 0.01

# optimizer
opt: "adamw"
weight_decay_filter: "norm_and_bias"
weight_decay: 0.3
use_nesterov: False

# amp
amp_level: "O2"
val_amp_level: 'O2'
loss_scale_type: 'fixed'
loss_scale: 1024

ema: True
